site_name: Exodocs
site_url: https://jxxcarlson.github.io/exo-docs
docs_dir: 'exo-docs'

theme: readthedocs

nav:
  - Home: 'index.md'
  - 'resources.md'
  - 'notes.md'
  - 'shares.md'
  - 'manila.md'
 